services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - './app:/app'
    command: 'bash -c "sleep 3 && npm start"'

  caddy:
    depends_on:
      - app
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'
