version: '3.8'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile          
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"    


  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/app  
    command: >
      make prepare-env dev         
    depends_on:
      - caddy
      