name: push

on:
    push:
        branches:
            - main

env:
  APP_IMAGE_NAME: isayli/devops-for-programmers-project-74

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Create .env file for docker
              run: cp .env.example .env

            - name: Install Docker Compose
              run: |
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.32.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
                docker-compose --version

            - name: Build image without push
              uses: docker/build-push-action@v3
              with:
                context: .
                file: Dockerfile.production
                push: false
                tags: ${{ env.APP_IMAGE_NAME }}:latest
                load: true

            - name: Run tests
              run: make compose-ci    
            
            - name: Login Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Push image
              run: docker push ${{ env.APP_IMAGE_NAME }}:latest