name: push

on:
    push:
        branches:
            - main

env:
  APP_IMAGE_NAME: isayli/devops-for-programmers-project-74

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Setup
        run: make setup      
      -
        name: Test Application
        run: make ci
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest              