name: push

on:
    push:
        branches:
            - main

env:
  APP_IMAGE_NAME: isayli/devops-for-programmers-project-74

jobs:
    check:
      name: Check code
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4
          
        - name: Buil project
          run: docker compose -f docker-compose.yml -f docker-compose.override.yml run --rm app make setup
          
        - name: Test project
          run: docker compose -f docker-compose.yml -f docker-compose.override.yml run --rm app make prepare-env test

    build_and_push:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
          attestations: write
          id-token: write
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.APP_IMAGE_NAME }}:latest
                tags: |
                  type=semver,pattern={{version}}
                  type=raw,value=latest,enable={{is_default_branch}}
                  type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'master') }}    

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile.production
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}                        
  